title: SIAM Student Chapter Delft
name: SIAM Student Chapter Delft
timezone: Europe/Amsterdam
markdown: kramdown
plugins:
  - jekyll-redirect-from

domain: sscdelft.github.io
author: SIAM Student Chapter Delft
email: siamsc-ewi@tudelft.nl
